### ISSUE TITLE
Hardcoded users who have left

### ISSUE THREAD

**Issue by cvalaas** [mozilla-iam/gsuite_cloud_users_driver#8]
https://github.com/mozilla-iam/gsuite_cloud_users_driver/blob/cefe027c87d429490a9c9c2535940d05ca6f3f48/gsuite_cloud_users_driver/driver.py#L23-L27

Some of these users have left Mozilla -- can we remove?

**Comment by cvalaas** [comment]
@gene1wood I think you're the only person in this org (mozilla-iam) with any permissions (the owners of this repo are all gone, I think). Andrew Morales just asked me to surface this for fixing at some point.

**Comment by gene1wood** [comment]
@cvalaas No, the SRE team now owns IAM and they have rights in this repo. @The-smooth-operator can speak to this ticket.

**Comment by limed** [comment]
PR https://github.com/mozilla-iam/gsuite_cloud_users_driver/pull/9 created

**Comment by The-smooth-operator** [comment]
@cvalaas thanks for cleaning up, really appreciated. 
I think we can close this PR on favor of PR #9 which is more accurate

**Comment by cvalaas** [comment]
thanks all!
